# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0019_auto_20180201_1610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='universalawardview',
            table='universal_award_transaction_matview',
        ),
    ]
