# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 19:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0020_auto_20180208_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalAwardTransactionView',
            fields=[
                ('keyword_string', models.TextField()),
                ('award_id_string', models.TextField()),
                ('award_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('type', models.TextField()),
                ('type_description', models.TextField()),
                ('piid', models.TextField()),
                ('fain', models.TextField()),
                ('uri', models.TextField()),
                ('total_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_obl_bin', models.TextField()),
                ('recipient_id', models.IntegerField()),
                ('recipient_name', models.TextField()),
                ('recipient_unique_id', models.TextField()),
                ('parent_recipient_unique_id', models.TextField()),
                ('business_categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('action_date', models.DateField()),
                ('transaction_action_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('transaction_fiscal_year', models.IntegerField()),
                ('period_of_performance_start_date', models.DateField()),
                ('period_of_performance_current_end_date', models.DateField()),
                ('face_value_loan_guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('original_loan_subsidy_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('awarding_agency_id', models.IntegerField()),
                ('funding_agency_id', models.IntegerField()),
                ('awarding_toptier_agency_name', models.TextField()),
                ('funding_toptier_agency_name', models.TextField()),
                ('awarding_subtier_agency_name', models.TextField()),
                ('funding_subtier_agency_name', models.TextField()),
                ('recipient_location_country_code', models.TextField()),
                ('recipient_location_country_name', models.TextField()),
                ('recipient_location_state_code', models.TextField()),
                ('recipient_location_county_code', models.TextField()),
                ('recipient_location_county_name', models.TextField()),
                ('recipient_location_zip5', models.TextField()),
                ('recipient_location_congressional_code', models.TextField()),
                ('pop_country_code', models.TextField()),
                ('pop_country_name', models.TextField()),
                ('pop_state_code', models.TextField()),
                ('pop_county_code', models.TextField()),
                ('pop_county_name', models.TextField()),
                ('pop_zip5', models.TextField()),
                ('pop_congressional_code', models.TextField()),
                ('cfda_number', models.TextField()),
                ('pulled_from', models.TextField()),
                ('type_of_contract_pricing', models.TextField()),
                ('extent_competed', models.TextField()),
                ('type_set_aside', models.TextField()),
                ('product_or_service_code', models.TextField()),
                ('product_or_service_description', models.TextField()),
                ('naics_code', models.TextField()),
                ('naics_description', models.TextField()),
            ],
            options={
                'db_table': 'universal_award_transaction_matview',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='universalawardview',
            table='universal_award_matview',
        ),
    ]
