DROP TABLE IF EXISTS transaction_fpds;

CREATE TABLE transaction_fpds AS
(

    SELECT
        *
    FROM
        dblink ('broker_server', '(
            SELECT
                detached_award_procurement_id,
                UPPER(detached_award_proc_unique) AS detached_award_proc_unique,
                UPPER(piid) AS award_id_piid,
                UPPER(agency_id) AS agency_id, --NOT USED IN DOWNLOAD
                UPPER(awarding_sub_tier_agency_c) AS awarding_sub_agency_code,
                UPPER(awarding_sub_tier_agency_n) AS awarding_sub_agency_name,
                UPPER(awarding_agency_code) AS awarding_agency_code,
                UPPER(awarding_agency_name) AS awarding_agency_name,
                UPPER(parent_award_id) AS parent_award_id,
                UPPER(award_modification_amendme) AS modification_number,
                UPPER(type_of_contract_pricing) AS type_of_contract_pricing_code,
                UPPER(type_of_contract_pric_desc) AS type_of_contract_pricing,
                UPPER(contract_award_type) AS award_type_code,
                UPPER(contract_award_type_desc) AS award_type,
                UPPER(naics) AS naics_code,
                UPPER(naics_description) AS naics_description,
                UPPER(awardee_or_recipient_uniqu) AS recipient_duns,
                UPPER(ultimate_parent_legal_enti) AS recipient_parent_name,
                UPPER(ultimate_parent_unique_ide) AS recipient_parent_duns,
                UPPER(award_description) AS award_description,
                UPPER(place_of_performance_zip4a) AS primary_place_of_performance_zip_4,
                UPPER(place_of_performance_zip5) AS place_of_performance_zip5, --NOT USED IN DOWNLOAD
                UPPER(place_of_perform_zip_last4) AS place_of_perform_zip_last4, --NOT USED IN DOWNLOAD
                UPPER(place_of_perform_city_name) AS primary_place_of_performance_city_name,
                UPPER(place_of_perform_county_co) AS place_of_perform_county_co, --NOT USED IN DOWNLOAD
                UPPER(place_of_perform_county_na) AS primary_place_of_performance_county_name,
                UPPER(place_of_performance_congr) AS primary_place_of_performance_congressional_district,
                UPPER(awardee_or_recipient_legal) AS recipient_name,
                UPPER(legal_entity_city_name) AS recipient_city_name,
                UPPER(legal_entity_county_code) AS recipient_county_code, --NOT USED IN DOWNLOAD
                UPPER(legal_entity_county_name) AS recipient_county_name, --NOT USED IN DOWNLOAD
                UPPER(legal_entity_state_code) AS recipient_state_code,
                UPPER(legal_entity_state_descrip) AS recipient_state_name,
                UPPER(legal_entity_zip4) AS recipient_zip_4_code,
                UPPER(legal_entity_zip5) AS recipient_zip5, --NOT USED IN DOWNLOAD
                UPPER(legal_entity_zip_last4) AS recipient_zip_last4, --NOT USED IN DOWNLOAD
                UPPER(legal_entity_congressional) AS recipient_congressional_district,
                UPPER(legal_entity_address_line1) AS recipient_address_line_1,
                UPPER(legal_entity_address_line2) AS recipient_address_line_2,
                UPPER(legal_entity_address_line3) AS recipient_address_line_3,
                UPPER(legal_entity_country_code) AS recipient_country_code,
                UPPER(legal_entity_country_name) AS recipient_country_name,
                UPPER(period_of_performance_star) AS period_of_performance_start_date,
                UPPER(period_of_performance_curr) AS period_of_performance_current_end_date,
                UPPER(period_of_perf_potential_e) AS period_of_performance_potential_end_date,
                UPPER(ordering_period_end_date) AS ordering_period_end_date,
                NULLIF(action_date, '''''''') AS action_date,
                UPPER(action_type) AS action_type_code,
                UPPER(action_type_description) AS action_type,
                federal_action_obligation,
                UPPER(current_total_value_award) AS current_total_value_award, --NOT USED IN DOWNLOAD
                UPPER(potential_total_value_awar) AS potential_total_value_awar, --NOT USED IN DOWNLOAD
                UPPER(total_obligated_amount) AS total_obligated_amount, --NOT USED IN DOWNLOAD
                UPPER(base_exercised_options_val) AS base_and_exercised_options_value,
                UPPER(base_and_all_options_value) AS base_and_all_options_value,
                UPPER(funding_sub_tier_agency_co) AS funding_sub_agency_code,
                UPPER(funding_sub_tier_agency_na) AS funding_sub_agency_name,
                UPPER(funding_office_code) AS funding_office_code,
                UPPER(funding_office_name) AS funding_office_name,
                UPPER(awarding_office_code) AS awarding_office_code,
                UPPER(awarding_office_name) AS awarding_office_name,
                UPPER(referenced_idv_agency_iden) AS parent_award_agency_id,
                UPPER(referenced_idv_agency_desc) AS parent_award_agency_name,
                UPPER(funding_agency_code) AS funding_agency_code,
                UPPER(funding_agency_name) AS funding_agency_name,
                UPPER(place_of_performance_locat) AS primary_place_of_performance_location_code,
                UPPER(place_of_performance_state) AS primary_place_of_performance_state_code,
                UPPER(place_of_perfor_state_desc) AS primary_place_of_performance_state_name,
                UPPER(place_of_perform_country_c) AS primary_place_of_performance_country_code,
                UPPER(place_of_perf_country_desc) AS primary_place_of_performance_country_name,
                UPPER(idv_type) AS idv_type_code,
                UPPER(idv_type_description) AS idv_type,
                UPPER(referenced_idv_type) AS parent_award_type_code,
                UPPER(referenced_idv_type_desc) AS parent_award_type,
                UPPER(vendor_doing_as_business_n) AS recipient_doing_business_as_name,
                UPPER(vendor_phone_number) AS recipient_phone_number,
                UPPER(vendor_fax_number) AS recipient_fax_number,
                UPPER(multiple_or_single_award_i) AS multiple_or_single_award_idv_code,
                UPPER(multiple_or_single_aw_desc) AS multiple_or_single_award_idv,
                UPPER(referenced_mult_or_single) AS parent_award_single_or_multiple_code,
                UPPER(referenced_mult_or_si_desc) AS parent_award_single_or_multiple,
                UPPER(type_of_idc) AS type_of_idc_code,
                UPPER(type_of_idc_description) AS type_of_idc,
                UPPER(a_76_fair_act_action) AS a76_fair_act_action_code,
                UPPER(a_76_fair_act_action_desc) AS a76_fair_act_action,
                UPPER(dod_claimant_program_code) AS dod_claimant_program_code,
                UPPER(dod_claimant_prog_cod_desc) AS dod_claimant_program_description,
                UPPER(clinger_cohen_act_planning) AS clinger_cohen_act_planning_code,
                UPPER(clinger_cohen_act_pla_desc) AS clinger_cohen_act_planning,
                UPPER(commercial_item_acquisitio) AS commercial_item_acquisition_procedures_code,
                UPPER(commercial_item_acqui_desc) AS commercial_item_acquisition_procedures,
                UPPER(commercial_item_test_progr) AS commercial_item_test_program_code,
                UPPER(commercial_item_test_desc) AS commercial_item_test_program,
                UPPER(consolidated_contract) AS consolidated_contract_code,
                UPPER(consolidated_contract_desc) AS consolidated_contract,
                UPPER(contingency_humanitarian_o) AS contingency_humanitarian_or_peacekeeping_operation_code,
                UPPER(contingency_humanitar_desc) AS contingency_humanitarian_or_peacekeeping_operation,
                UPPER(contract_bundling) AS contract_bundling_code,
                UPPER(contract_bundling_descrip) AS contract_bundling,
                UPPER(contract_financing) AS contract_financing_code,
                UPPER(contract_financing_descrip) AS contract_financing,
                UPPER(contracting_officers_deter) AS contracting_officers_determination_of_business_size_code,
                UPPER(contracting_officers_desc) AS contracting_officers_determination_of_business_size,
                UPPER(cost_accounting_standards) AS cost_accounting_standards_clause_code,
                UPPER(cost_accounting_stand_desc) AS cost_accounting_standards_clause,
                UPPER(cost_or_pricing_data) AS cost_or_pricing_data_code,
                UPPER(cost_or_pricing_data_desc) AS cost_or_pricing_data,
                UPPER(country_of_product_or_serv) AS country_of_product_or_service_origin_code,
                UPPER(country_of_product_or_desc) AS country_of_product_or_service_origin,
                UPPER(davis_bacon_act) AS davis_bacon_act_code,
                UPPER(davis_bacon_act_descrip) AS davis_bacon_act,
                UPPER(evaluated_preference) AS evaluated_preference_code,
                UPPER(evaluated_preference_desc) AS evaluated_preference,
                UPPER(extent_competed) AS extent_competed_code,
                UPPER(extent_compete_description) AS extent_competed,
                UPPER(fed_biz_opps) AS fed_biz_opps_code,
                UPPER(fed_biz_opps_description) AS fed_biz_opps,
                UPPER(foreign_funding) AS foreign_funding,
                UPPER(foreign_funding_desc) AS foreign_funding_desc, --NOT USED IN DOWNLOAD
                UPPER(government_furnished_equip) AS gfe_gfp_code,
                UPPER(government_furnished_desc) AS gfe_gfp,
                UPPER(information_technology_com) AS information_technology_commercial_item_category_code,
                UPPER(information_technolog_desc) AS information_technology_commercial_item_category,
                UPPER(interagency_contracting_au) AS interagency_contracting_authority_code,
                UPPER(interagency_contract_desc) AS interagency_contracting_authority,
                UPPER(local_area_set_aside) AS local_area_set_aside_code,
                UPPER(local_area_set_aside_desc) AS local_area_set_aside,
                UPPER(major_program) AS major_program,
                UPPER(purchase_card_as_payment_m) AS purchase_card_as_payment_method_code,
                UPPER(purchase_card_as_paym_desc) AS purchase_card_as_payment_method,
                UPPER(multi_year_contract) AS multi_year_contract_code,
                UPPER(multi_year_contract_desc) AS multi_year_contract,
                UPPER(national_interest_action) AS national_interest_action_code,
                UPPER(national_interest_desc) AS national_interest_action,
                UPPER(number_of_actions) AS number_of_actions,
                UPPER(number_of_offers_received) AS number_of_offers_received,
                UPPER(other_statutory_authority) AS other_statutory_authority,
                UPPER(performance_based_service) AS performance_based_service_acquisition_code,
                UPPER(performance_based_se_desc) AS performance_based_service_acquisition,
                UPPER(place_of_manufacture) AS place_of_manufacture_code,
                UPPER(place_of_manufacture_desc) AS place_of_manufacture,
                UPPER(price_evaluation_adjustmen) AS price_evaluation_adjustment_preference_percent_difference,
                UPPER(product_or_service_code) AS product_or_service_code,
                UPPER(product_or_service_co_desc) AS product_or_service_code_description,
                UPPER(program_acronym) AS program_acronym,
                UPPER(other_than_full_and_open_c) AS other_than_full_and_open_competition_code,
                UPPER(other_than_full_and_o_desc) AS other_than_full_and_open_competition,
                UPPER(recovered_materials_sustai) AS recovered_materials_sustainability_code,
                UPPER(recovered_materials_s_desc) AS recovered_materials_sustainability,
                UPPER(research) AS research_code,
                UPPER(research_description) AS research,
                UPPER(sea_transportation) AS sea_transportation_code,
                UPPER(sea_transportation_desc) AS sea_transportation,
                UPPER(service_contract_act) AS service_contract_act_code,
                UPPER(service_contract_act_desc) AS service_contract_act,
                COALESCE(NULLIF(small_business_competitive, ''''), ''0'')::BOOLEAN AS small_business_competitiveness_demonstration_program,
                UPPER(solicitation_identifier) AS solicitation_identifier,
                UPPER(solicitation_procedures) AS solicitation_procedures_code,
                UPPER(solicitation_procedur_desc) AS solicitation_procedures,
                UPPER(fair_opportunity_limited_s) AS fair_opportunity_limited_sources_code,
                UPPER(fair_opportunity_limi_desc) AS fair_opportunity_limited_sources,
                UPPER(subcontracting_plan) AS subcontracting_plan_code,
                UPPER(subcontracting_plan_desc) AS subcontracting_plan,
                UPPER(program_system_or_equipmen) AS dod_acquisition_program_code,
                UPPER(program_system_or_equ_desc) AS dod_acquisition_program_description,
                UPPER(type_set_aside) AS type_of_set_aside_code,
                UPPER(type_set_aside_description) AS type_of_set_aside,
                UPPER(epa_designated_product) AS epa_designated_product_code,
                UPPER(epa_designated_produc_desc) AS epa_designated_product,
                UPPER(walsh_healey_act) AS walsh_healey_act_code,
                UPPER(walsh_healey_act_descrip) AS walsh_healey_act,
                UPPER(transaction_number) AS transaction_number,
                UPPER(sam_exception) AS sam_exception,
                UPPER(sam_exception_description) AS sam_exception_description, --NOT USED IN DOWNLOAD
                COALESCE(NULLIF(city_local_government, ''''), ''0'')::BOOLEAN AS city_local_government,
                COALESCE(NULLIF(county_local_government, ''''), ''0'')::BOOLEAN AS county_local_government,
                COALESCE(NULLIF(inter_municipal_local_gove, ''''), ''0'')::BOOLEAN AS inter_municipal_local_government,
                COALESCE(NULLIF(local_government_owned, ''''), ''0'')::BOOLEAN AS local_government_owned,
                COALESCE(NULLIF(municipality_local_governm, ''''), ''0'')::BOOLEAN AS municipality_local_government,
                COALESCE(NULLIF(school_district_local_gove, ''''), ''0'')::BOOLEAN AS school_district_local_government,
                COALESCE(NULLIF(township_local_government, ''''), ''0'')::BOOLEAN AS township_local_government,
                COALESCE(NULLIF(us_state_government, ''''), ''0'')::BOOLEAN AS us_state_government,
                COALESCE(NULLIF(us_federal_government, ''''), ''0'')::BOOLEAN AS us_federal_government,
                COALESCE(NULLIF(federal_agency, ''''), ''0'')::BOOLEAN AS federal_agency,
                COALESCE(NULLIF(federally_funded_research, ''''), ''0'')::BOOLEAN AS federally_funded_research_and_development_corp,
                COALESCE(NULLIF(us_tribal_government, ''''), ''0'')::BOOLEAN AS us_tribal_government,
                COALESCE(NULLIF(foreign_government, ''''), ''0'')::BOOLEAN AS foreign_government,
                COALESCE(NULLIF(community_developed_corpor, ''''), ''0'')::BOOLEAN AS community_developed_corporation_owned_firm,
                COALESCE(NULLIF(labor_surplus_area_firm, ''''), ''0'')::BOOLEAN AS labor_surplus_area_firm,
                COALESCE(NULLIF(corporate_entity_not_tax_e, ''''), ''0'')::BOOLEAN AS corporate_entity_not_tax_exempt,
                COALESCE(NULLIF(corporate_entity_tax_exemp, ''''), ''0'')::BOOLEAN AS corporate_entity_tax_exempt,
                COALESCE(NULLIF(partnership_or_limited_lia, ''''), ''0'')::BOOLEAN AS partnership_or_limited_liability_partnership,
                COALESCE(NULLIF(sole_proprietorship, ''''), ''0'')::BOOLEAN AS sole_proprietorship,
                COALESCE(NULLIF(small_agricultural_coopera, ''''), ''0'')::BOOLEAN AS small_agricultural_cooperative,
                COALESCE(NULLIF(international_organization, ''''), ''0'')::BOOLEAN AS international_organization,
                COALESCE(NULLIF(us_government_entity, ''''), ''0'')::BOOLEAN AS us_government_entity,
                COALESCE(NULLIF(emerging_small_business, ''''), ''0'')::BOOLEAN AS emerging_small_business,
                COALESCE(NULLIF(c8a_program_participant, ''''), ''0'')::BOOLEAN AS c8a_program_participant,
                COALESCE(NULLIF(sba_certified_8_a_joint_ve, ''''), ''0'')::BOOLEAN AS sba_certified_8a_joint_venture,
                COALESCE(NULLIF(dot_certified_disadvantage, ''''), ''0'')::BOOLEAN AS dot_certified_disadvantage,
                COALESCE(NULLIF(self_certified_small_disad, ''''), ''0'')::BOOLEAN AS self_certified_small_disadvantaged_business,
                COALESCE(NULLIF(historically_underutilized, ''''), ''0'')::BOOLEAN AS historically_underutilized_business_zone_hubzone_firm,
                COALESCE(NULLIF(small_disadvantaged_busine, ''''), ''0'')::BOOLEAN AS small_disadvantaged_busine,
                COALESCE(NULLIF(the_ability_one_program, ''''), ''0'')::BOOLEAN AS the_ability_one_program,
                COALESCE(NULLIF(historically_black_college, ''''), ''0'')::BOOLEAN AS historically_black_college,
                COALESCE(NULLIF(c1862_land_grant_college, ''''), ''0'')::BOOLEAN AS c1862_land_grant_college,
                COALESCE(NULLIF(c1890_land_grant_college, ''''), ''0'')::BOOLEAN AS c1890_land_grant_college,
                COALESCE(NULLIF(c1994_land_grant_college, ''''), ''0'')::BOOLEAN AS c1994_land_grant_college,
                COALESCE(NULLIF(minority_institution, ''''), ''0'')::BOOLEAN AS minority_institution,
                COALESCE(NULLIF(private_university_or_coll, ''''), ''0'')::BOOLEAN AS private_university_or_college,
                COALESCE(NULLIF(school_of_forestry, ''''), ''0'')::BOOLEAN AS school_of_forestry,
                COALESCE(NULLIF(state_controlled_instituti, ''''), ''0'')::BOOLEAN AS state_controlled_institution_of_higher_learning,
                COALESCE(NULLIF(tribal_college, ''''), ''0'')::BOOLEAN AS tribal_college,
                COALESCE(NULLIF(veterinary_college, ''''), ''0'')::BOOLEAN AS veterinary_college,
                COALESCE(NULLIF(educational_institution, ''''), ''0'')::BOOLEAN AS educational_institution,
                COALESCE(NULLIF(alaskan_native_servicing_i, ''''), ''0'')::BOOLEAN AS alaskan_native_servicing_institution,
                COALESCE(NULLIF(community_development_corp, ''''), ''0'')::BOOLEAN AS community_development_corporation,
                COALESCE(NULLIF(native_hawaiian_servicing, ''''), ''0'')::BOOLEAN AS native_hawaiian_servicing_institution,
                COALESCE(NULLIF(domestic_shelter, ''''), ''0'')::BOOLEAN AS domestic_shelter,
                COALESCE(NULLIF(manufacturer_of_goods, ''''), ''0'')::BOOLEAN AS manufacturer_of_goods,
                COALESCE(NULLIF(hospital_flag, ''''), ''0'')::BOOLEAN AS hospital_flag,
                COALESCE(NULLIF(veterinary_hospital, ''''), ''0'')::BOOLEAN AS veterinary_hospital,
                COALESCE(NULLIF(hispanic_servicing_institu, ''''), ''0'')::BOOLEAN AS hispanic_servicing_institution,
                COALESCE(NULLIF(foundation, ''''), ''0'')::BOOLEAN AS foundation,
                COALESCE(NULLIF(woman_owned_business, ''''), ''0'')::BOOLEAN AS woman_owned_business,
                COALESCE(NULLIF(minority_owned_business, ''''), ''0'')::BOOLEAN AS minority_owned_business,
                COALESCE(NULLIF(women_owned_small_business, ''''), ''0'')::BOOLEAN AS women_owned_small_business,
                COALESCE(NULLIF(economically_disadvantaged, ''''), ''0'')::BOOLEAN AS economically_disadvantaged_women_owned_small_business,
                COALESCE(NULLIF(joint_venture_women_owned, ''''), ''0'')::BOOLEAN AS joint_venture_women_owned_small_business,
                COALESCE(NULLIF(joint_venture_economically, ''''), ''0'')::BOOLEAN AS joint_venture_economic_disadvantaged_women_owned_small_bus,
                COALESCE(NULLIF(veteran_owned_business, ''''), ''0'')::BOOLEAN AS veteran_owned_business,
                COALESCE(NULLIF(service_disabled_veteran_o, ''''), ''0'')::BOOLEAN AS service_disabled_veteran_owned_business,
                COALESCE(NULLIF(contracts, ''''), ''0'')::BOOLEAN AS receives_contracts,
                COALESCE(NULLIF(grants, ''''), ''0'')::BOOLEAN AS receives_grants,
                COALESCE(NULLIF(receives_contracts_and_gra, ''''), ''0'')::BOOLEAN AS receives_contracts_and_grants,
                COALESCE(NULLIF(airport_authority, ''''), ''0'')::BOOLEAN AS airport_authority,
                COALESCE(NULLIF(council_of_governments, ''''), ''0'')::BOOLEAN AS council_of_governments,
                COALESCE(NULLIF(housing_authorities_public, ''''), ''0'')::BOOLEAN AS housing_authorities_public_tribal,
                COALESCE(NULLIF(interstate_entity, ''''), ''0'')::BOOLEAN AS interstate_entity,
                COALESCE(NULLIF(planning_commission, ''''), ''0'')::BOOLEAN AS planning_commission,
                COALESCE(NULLIF(port_authority, ''''), ''0'')::BOOLEAN AS port_authority,
                COALESCE(NULLIF(transit_authority, ''''), ''0'')::BOOLEAN AS transit_authority,
                COALESCE(NULLIF(subchapter_s_corporation, ''''), ''0'')::BOOLEAN AS subchapter_scorporation,
                COALESCE(NULLIF(limited_liability_corporat, ''''), ''0'')::BOOLEAN AS limited_liability_corporation,
                COALESCE(NULLIF(foreign_owned_and_located, ''''), ''0'')::BOOLEAN AS foreign_owned_and_located,
                COALESCE(NULLIF(american_indian_owned_busi, ''''), ''0'')::BOOLEAN AS american_indian_owned_business,
                COALESCE(NULLIF(alaskan_native_owned_corpo, ''''), ''0'')::BOOLEAN AS alaskan_native_owned_corporation_or_firm,
                COALESCE(NULLIF(indian_tribe_federally_rec, ''''), ''0'')::BOOLEAN AS indian_tribe_federally_recognized,
                COALESCE(NULLIF(native_hawaiian_owned_busi, ''''), ''0'')::BOOLEAN AS native_hawaiian_owned_business,
                COALESCE(NULLIF(tribally_owned_business, ''''), ''0'')::BOOLEAN AS tribally_owned_business,
                COALESCE(NULLIF(asian_pacific_american_own, ''''), ''0'')::BOOLEAN AS asian_pacific_american_owned_business,
                COALESCE(NULLIF(black_american_owned_busin, ''''), ''0'')::BOOLEAN AS black_american_owned_business,
                COALESCE(NULLIF(hispanic_american_owned_bu, ''''), ''0'')::BOOLEAN AS hispanic_american_owned_business,
                COALESCE(NULLIF(native_american_owned_busi, ''''), ''0'')::BOOLEAN AS native_american_owned_business,
                COALESCE(NULLIF(subcontinent_asian_asian_i, ''''), ''0'')::BOOLEAN AS subcontinent_asian_asian_indian_american_owned_business,
                COALESCE(NULLIF(other_minority_owned_busin, ''''), ''0'')::BOOLEAN AS other_minority_owned_business,
                COALESCE(NULLIF(for_profit_organization, ''''), ''0'')::BOOLEAN AS for_profit_organization,
                COALESCE(NULLIF(nonprofit_organization, ''''), ''0'')::BOOLEAN AS nonprofit_organization,
                COALESCE(NULLIF(other_not_for_profit_organ, ''''), ''0'')::BOOLEAN AS other_not_for_profit_organization,
                COALESCE(NULLIF(us_local_government, ''''), ''0'')::BOOLEAN AS us_local_government,
                UPPER(referenced_idv_modificatio) AS parent_award_modification_number,
                UPPER(undefinitized_action) AS undefinitized_action_code,
                UPPER(undefinitized_action_desc) AS undefinitized_action,
                UPPER(domestic_or_foreign_entity) AS domestic_or_foreign_entity_code,
                UPPER(domestic_or_foreign_e_desc) AS domestic_or_foreign_entity,
                UPPER(annual_revenue) AS annual_revenue, --NOT USED IN DOWNLOAD
                UPPER(division_name) AS division_name, --NOT USED IN DOWNLOAD
                UPPER(division_number_or_office) AS division_number_or_office, --NOT USED IN DOWNLOAD
                UPPER(number_of_employees) AS number_of_employees, --NOT USED IN DOWNLOAD
                UPPER(vendor_alternate_name) AS vendor_alternate_name, --NOT USED IN DOWNLOAD
                UPPER(vendor_alternate_site_code) AS vendor_alternate_site_code, --NOT USED IN DOWNLOAD
                UPPER(vendor_enabled) AS vendor_enabled, --NOT USED IN DOWNLOAD
                UPPER(vendor_legal_org_name) AS vendor_legal_org_name, --NOT USED IN DOWNLOAD
                UPPER(vendor_location_disabled_f) AS vendor_location_disabled_f, --NOT USED IN DOWNLOAD
                UPPER(vendor_site_code) AS vendor_site_code, --NOT USED IN DOWNLOAD
                UPPER(pulled_from) AS pulled_from, --NOT USED IN DOWNLOAD
                UPPER(last_modified) AS last_modified_date, --NOT USED IN DOWNLOAD
                UPPER(initial_report_date) AS initial_report_date, --NOT USED IN DOWNLOAD
                UPPER(referenced_idv_agency_name) AS referenced_idv_agency_name, --NOT USED IN DOWNLOAD
                UPPER(referenced_multi_or_single) AS referenced_multi_or_single, --NOT USED IN DOWNLOAD
                UPPER(award_or_idv_flag) AS award_or_idv_flag, --NOT USED IN DOWNLOAD
                UPPER(place_of_perform_country_n) AS place_of_perform_country_n, --NOT USED IN DOWNLOAD
                UPPER(place_of_perform_state_nam) AS place_of_perform_state_nam, --NOT USED IN DOWNLOAD
                created_at,
                updated_at
            FROM detached_award_procurement
        )') AS transaction_contracts
    (
        detached_award_procurement_id int,
        detached_award_proc_unique text,
        award_id_piid text,
        agency_id text,
        awarding_sub_agency_code text,
        awarding_sub_agency_name text,
        awarding_agency_code text,
        awarding_agency_name text,
        parent_award_id text,
        modification_number text,
        type_of_contract_pricing_code text,
        type_of_contract_pricing text,
        award_type_code text,
        award_type text,
        naics_code text,
        naics_description text,
        recipient_duns text,
        recipient_parent_name text,
        recipient_parent_duns text,
        award_description text,
        primary_place_of_performance_zip_4 text,
        place_of_performance_zip5 text,
        place_of_perform_zip_last4 text,
        primary_place_of_performance_city_name text,
        place_of_perform_county_co text,
        primary_place_of_performance_county_name text,
        primary_place_of_performance_congressional_district text,
        recipient_name text,
        recipient_city_name text,
        recipient_county_code text,
        recipient_county_name text,
        recipient_state_code text,
        recipient_state_name text,
        recipient_zip_4_code text,
        recipient_zip5 text,
        recipient_zip_last4 text,
        recipient_congressional_district text,
        recipient_address_line_1 text,
        recipient_address_line_2 text,
        recipient_address_line_3 text,
        recipient_country_code text,
        recipient_country_name text,
        period_of_performance_start_date text,
        period_of_performance_current_end_date text,
        period_of_performance_potential_end_date text,
        ordering_period_end_date text,
        action_date text,
        action_type_code text,
        action_type text,
        federal_action_obligation numeric,
        current_total_value_award text,
        potential_total_value_awar text,
        total_obligated_amount text,
        base_and_exercised_options_value text,
        base_and_all_options_value text,
        funding_sub_agency_code text,
        funding_sub_agency_name text,
        funding_office_code text,
        funding_office_name text,
        awarding_office_code text,
        awarding_office_name text,
        parent_award_agency_id text,
        parent_award_agency_name text,
        funding_agency_code text,
        funding_agency_name text,
        primary_place_of_performance_location_code text,
        primary_place_of_performance_state_code text,
        primary_place_of_performance_state_name text,
        primary_place_of_performance_country_code text,
        primary_place_of_performance_country_name text,
        idv_type_code text,
        idv_type text,
        parent_award_type_code text,
        parent_award_type text,
        recipient_doing_business_as_name text,
        recipient_phone_number text,
        recipient_fax_number text,
        multiple_or_single_award_idv_code text,
        multiple_or_single_award_idv text,
        parent_award_single_or_multiple_code text,
        parent_award_single_or_multiple text,
        type_of_idc_code text,
        type_of_idc text,
        a76_fair_act_action_code text,
        a76_fair_act_action text,
        dod_claimant_program_code text,
        dod_claimant_program_description text,
        clinger_cohen_act_planning_code text,
        clinger_cohen_act_planning text,
        commercial_item_acquisition_procedures_code text,
        commercial_item_acquisition_procedures text,
        commercial_item_test_program_code text,
        commercial_item_test_program text,
        consolidated_contract_code text,
        consolidated_contract text,
        contingency_humanitarian_or_peacekeeping_operation_code text,
        contingency_humanitarian_or_peacekeeping_operation text,
        contract_bundling_code text,
        contract_bundling text,
        contract_financing_code text,
        contract_financing text,
        contracting_officers_determination_of_business_size_code text,
        contracting_officers_determination_of_business_size text,
        cost_accounting_standards_clause_code text,
        cost_accounting_standards_clause text,
        cost_or_pricing_data_code text,
        cost_or_pricing_data text,
        country_of_product_or_service_origin_code text,
        country_of_product_or_service_origin text,
        davis_bacon_act_code text,
        davis_bacon_act text,
        evaluated_preference_code text,
        evaluated_preference text,
        extent_competed_code text,
        extent_competed text,
        fed_biz_opps_code text,
        fed_biz_opps text,
        foreign_funding text,
        foreign_funding_desc text,
        gfe_gfp_code text,
        gfe_gfp text,
        information_technology_commercial_item_category_code text,
        information_technology_commercial_item_category text,
        interagency_contracting_authority_code text,
        interagency_contracting_authority text,
        local_area_set_aside_code text,
        local_area_set_aside text,
        major_program text,
        purchase_card_as_payment_method_code text,
        purchase_card_as_payment_method text,
        multi_year_contract_code text,
        multi_year_contract text,
        national_interest_action_code text,
        national_interest_action text,
        number_of_actions text,
        number_of_offers_received text,
        other_statutory_authority text,
        performance_based_service_acquisition_code text,
        performance_based_service_acquisition text,
        place_of_manufacture_code text,
        place_of_manufacture text,
        price_evaluation_adjustment_preference_percent_difference text,
        product_or_service_code text,
        product_or_service_code_description text,
        program_acronym text,
        other_than_full_and_open_competition_code text,
        other_than_full_and_open_competition text,
        recovered_materials_sustainability_code text,
        recovered_materials_sustainability text,
        research_code text,
        research text,
        sea_transportation_code text,
        sea_transportation text,
        service_contract_act_code text,
        service_contract_act text,
        small_business_competitiveness_demonstration_program boolean,
        solicitation_identifier text,
        solicitation_procedures_code text,
        solicitation_procedures text,
        fair_opportunity_limited_sources_code text,
        fair_opportunity_limited_sources text,
        subcontracting_plan_code text,
        subcontracting_plan text,
        dod_acquisition_program_code text,
        dod_acquisition_program_description text,
        type_of_set_aside_code text,
        type_of_set_aside text,
        epa_designated_product_code text,
        epa_designated_product text,
        walsh_healey_act_code text,
        walsh_healey_act text,
        transaction_number text,
        sam_exception text,
        sam_exception_description text,
        city_local_government boolean,
        county_local_government boolean,
        inter_municipal_local_government boolean,
        local_government_owned boolean,
        municipality_local_government boolean,
        school_district_local_government boolean,
        township_local_government boolean,
        us_state_government boolean,
        us_federal_government boolean,
        federal_agency boolean,
        federally_funded_research_and_development_corp boolean,
        us_tribal_government boolean,
        foreign_government boolean,
        community_developed_corporation_owned_firm boolean,
        labor_surplus_area_firm boolean,
        corporate_entity_not_tax_exempt boolean,
        corporate_entity_tax_exempt boolean,
        partnership_or_limited_liability_partnership boolean,
        sole_proprietorship boolean,
        small_agricultural_cooperative boolean,
        international_organization boolean,
        us_government_entity boolean,
        emerging_small_business boolean,
        c8a_program_participant boolean,
        sba_certified_8a_joint_venture boolean,
        dot_certified_disadvantage boolean,
        self_certified_small_disadvantaged_business boolean,
        historically_underutilized_business_zone_hubzone_firm boolean,
        small_disadvantaged_busine boolean,
        the_ability_one_program boolean,
        historically_black_college boolean,
        c1862_land_grant_college boolean,
        c1890_land_grant_college boolean,
        c1994_land_grant_college boolean,
        minority_institution boolean,
        private_university_or_college boolean,
        school_of_forestry boolean,
        state_controlled_institution_of_higher_learning boolean,
        tribal_college boolean,
        veterinary_college boolean,
        educational_institution boolean,
        alaskan_native_servicing_institution boolean,
        community_development_corporation boolean,
        native_hawaiian_servicing_institution boolean,
        domestic_shelter boolean,
        manufacturer_of_goods boolean,
        hospital_flag boolean,
        veterinary_hospital boolean,
        hispanic_servicing_institution boolean,
        foundation boolean,
        woman_owned_business boolean,
        minority_owned_business boolean,
        women_owned_small_business boolean,
        economically_disadvantaged_women_owned_small_business boolean,
        joint_venture_women_owned_small_business boolean,
        joint_venture_economic_disadvantaged_women_owned_small_bus boolean,
        veteran_owned_business boolean,
        service_disabled_veteran_owned_business boolean,
        receives_contracts boolean,
        receives_grants boolean,
        receives_contracts_and_grants boolean,
        airport_authority boolean,
        council_of_governments boolean,
        housing_authorities_public_tribal boolean,
        interstate_entity boolean,
        planning_commission boolean,
        port_authority boolean,
        transit_authority boolean,
        subchapter_scorporation boolean,
        limited_liability_corporation boolean,
        foreign_owned_and_located boolean,
        american_indian_owned_business boolean,
        alaskan_native_owned_corporation_or_firm boolean,
        indian_tribe_federally_recognized boolean,
        native_hawaiian_owned_business boolean,
        tribally_owned_business boolean,
        asian_pacific_american_owned_business boolean,
        black_american_owned_business boolean,
        hispanic_american_owned_business boolean,
        native_american_owned_business boolean,
        subcontinent_asian_asian_indian_american_owned_business boolean,
        other_minority_owned_business boolean,
        for_profit_organization boolean,
        nonprofit_organization boolean,
        other_not_for_profit_organization boolean,
        us_local_government boolean,
        parent_award_modification_number boolean,
        undefinitized_action_code boolean,
        undefinitized_action boolean,
        domestic_or_foreign_entity_code boolean,
        domestic_or_foreign_entity boolean,
        annual_revenue boolean,
        division_name boolean,
        division_number_or_office boolean,
        number_of_employees boolean,
        vendor_alternate_name boolean,
        vendor_alternate_site_code boolean,
        vendor_enabled boolean,
        vendor_legal_org_name boolean,
        vendor_location_disabled_f boolean,
        vendor_site_code boolean,
        pulled_from boolean,
        last_modified_date boolean,
        initial_report_date boolean,
        referenced_idv_agency_name text,
        referenced_multi_or_single text,
        award_or_idv_flag text,
        place_of_perform_country_n text,
        place_of_perform_state_nam text,
        created_at timestamp without time zone,
        updated_at timestamp without time zone
    )
);