DROP TABLE IF EXISTS transaction_fabs;

CREATE TABLE transaction_fabs AS
(

    SELECT
        *
    FROM
        (SELECT
            published_award_financial_assistance_id,
            NULLIF(action_date, '''') AS action_date,
            UPPER(action_type) AS action_type_code,
            UPPER(assistance_type) AS assistance_type_code,
            UPPER(award_description) AS award_description,
            UPPER(awardee_or_recipient_legal) AS prime_awardee_name,
            UPPER(awardee_or_recipient_uniqu) AS prime_awardee_duns,
            UPPER(awarding_agency_code) AS awarding_agency_code,
            UPPER(awarding_office_code) AS awarding_office_code,
            UPPER(awarding_sub_tier_agency_c) AS awarding_sub_agency_code,
            UPPER(award_modification_amendme) AS modification_number,
            UPPER(business_funds_indicator) AS business_funds_indicator_code,
            UPPER(business_types) AS business_types_code,
            UPPER(cfda_number) AS cfda_number,
            UPPER(correction_late_delete_ind) AS correction_late_delete_ind, --NOT USED IN DOWNLOAD
            face_value_of_loan,
            UPPER(fain) AS award_id_fain,
            federal_action_obligation,
            UPPER(fiscal_year_and_quarter_co) AS fiscal_year_and_quarter_correction,
            UPPER(funding_agency_code) AS funding_agency_code,
            UPPER(funding_office_code) AS funding_office_code,
            UPPER(funding_sub_tier_agency_co) AS funding_sub_agency_code,
            UPPER(legal_entity_address_line1) AS recipient_address_line_1,
            UPPER(legal_entity_address_line2) AS recipient_address_line_2,
            UPPER(legal_entity_address_line3) AS recipient_address_line_3,
            UPPER(legal_entity_country_code) AS recipient_country_code,
            UPPER(legal_entity_foreign_city) AS recipient_foreign_city_name,
            UPPER(legal_entity_foreign_posta) AS recipient_foreign_postal_code,
            UPPER(legal_entity_foreign_provi) AS recipient_foreign_province_name,
            UPPER(legal_entity_zip5) AS recipient_zip_code,
            UPPER(legal_entity_zip_last4) AS recipient_zip_last_4_code,
            non_federal_funding_amount,
            original_subsidy_cost   ,
            UPPER(period_of_performance_curr) AS period_of_performance_current_end_date,
            UPPER(period_of_performance_star) AS period_of_performance_start_date,
            UPPER(place_of_performance_code) AS primary_place_of_performance_code,
            UPPER(place_of_performance_congr) AS primary_place_of_performance_congressional_district,
            UPPER(place_of_perform_country_c) AS primary_place_of_performance_country_code,
            UPPER(place_of_performance_forei) AS primary_place_of_performance_foreign_location,
            UPPER(place_of_performance_zip4a) AS primary_place_of_performance_zip_4,
            record_type_code,
            UPPER(sai_number) AS sai_number,
            UPPER(uri) AS award_id_uri,
            UPPER(legal_entity_congressional) AS recipient_congressional_district,
            UPPER(total_funding_amount) AS total_funding_amount,
            UPPER(cfda_title) AS cfda_title,
            UPPER(awarding_agency_name) AS awarding_agency_name,
            UPPER(awarding_sub_tier_agency_n) AS awarding_sub_agency_name,
            UPPER(funding_agency_name) AS funding_agency_name,
            UPPER(funding_sub_tier_agency_na) AS funding_sub_agency_name,
            is_historical,
            UPPER(place_of_perform_county_na) AS primary_place_of_performance_county_name,
            UPPER(place_of_perform_state_nam) AS primary_place_of_performance_state_name,
            UPPER(place_of_performance_city) AS primary_place_of_performance_city_name,
            UPPER(legal_entity_city_name) AS recipient_city_name,
            UPPER(legal_entity_county_code) AS recipient_county_code,
            UPPER(legal_entity_county_name) AS recipient_county_name,
            UPPER(legal_entity_state_code) AS recipient_state_code,
            UPPER(legal_entity_state_name) AS recipient_state_name,
            last_modified_date,
            UPPER(afa_generated_unique) AS afa_generated_unique, --NOT USED IN DOWNLOAD
            is_active, --NOT USED IN DOWNLOAD
            UPPER(legal_entity_country_name) AS recipient_country_name,
            UPPER(place_of_perform_country_n) AS primary_place_of_performance_country_name,
            UPPER(place_of_perform_county_co) AS primary_place_of_performance_county_code,
            UPPER(awarding_office_name) AS awarding_office_name,
            UPPER(funding_office_name) AS funding_office_name,
            UPPER(legal_entity_city_code) AS recipient_city_code,
            UPPER(legal_entity_foreign_descr) AS recipient_foreign_description, --NOT USED IN DOWNLOAD
            submission_id, --NOT USED IN DOWNLOAD
            UPPER(place_of_perfor_state_code) AS place_of_perfor_state_code, --NOT USED IN DOWNLOAD
            UPPER(place_of_performance_zip5) AS place_of_performance_zip5, --NOT USED IN DOWNLOAD
            UPPER(place_of_perform_zip_last4) AS place_of_perform_zip_last4, --NOT USED IN DOWNLOAD
            created_at, --NOT USED IN DOWNLOAD
            updated_at --NOT USED IN DOWNLOAD
        FROM published_award_financial_assistance
        WHERE is_active = True) AS transaction_assistance
    (
        published_award_financial_assistance_id integer,
        action_date text,
        action_type_code text,
        assistance_type_code text,
        award_description text,
        prime_awardee_name text,
        prime_awardee_duns text,
        awarding_agency_code text,
        awarding_office_code text,
        awarding_sub_agency_code text,
        modification_number text,
        business_funds_indicator_code text,
        business_types_code text,
        cfda_number text,
        correction_late_delete_ind text,
        face_value_of_loan numeric,
        award_id_fain text,
        federal_action_obligation numeric,
        fiscal_year_and_quarter_correction text,
        funding_agency_code text,
        funding_office_code text,
        funding_sub_agency_code text,
        recipient_address_line_1 text,
        recipient_address_line_2 text,
        recipient_address_line_3 text,
        recipient_country_code text,
        recipient_foreign_city_name text,
        recipient_foreign_postal_code text,
        recipient_foreign_province_name text,
        recipient_zip_code text,
        recipient_zip_last_4_code text,
        non_federal_funding_amount numeric,
        original_subsidy_cost numeric,
        period_of_performance_current_end_date text,
        period_of_performance_start_date text,
        primary_place_of_performance_code text,
        primary_place_of_performance_congressional_district text,
        primary_place_of_performance_country_code text,
        primary_place_of_performance_foreign_location text,
        primary_place_of_performance_zip_4 text,
        record_type_code integer,
        sai_number text,
        award_id_uri text,
        recipient_congressional_district text,
        total_funding_amount text,
        cfda_title text,
        awarding_agency_name text,
        awarding_sub_agency_name text,
        funding_agency_name text,
        funding_sub_agency_name text,
        is_historical boolean,
        primary_place_of_performance_county_name text,
        primary_place_of_performance_state_name text,
        primary_place_of_performance_city_name text,
        recipient_city_name text,
        recipient_county_code text,
        recipient_county_name text,
        recipient_state_code text,
        recipient_state_name text,
        last_modified_date timestamp without time zone,
        afa_generated_unique text,
        is_active boolean,
        recipient_country_name text,
        primary_place_of_performance_country_name text,
        primary_place_of_performance_county_code text,
        awarding_office_name text,
        funding_office_name text,
        recipient_city_code text,
        legal_entity_foreign_descr text,
        submission_id numeric,
        place_of_perfor_state_code text,
        place_of_performance_zip5 text,
        place_of_perform_zip_last4 text,
        created_at timestamp without time zone,
        updated_at timestamp without time zone
    )
);